export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_FAILED_LOGIN = "SET_FAILED_LOGIN";
export const SET_LOGOUT = "SET_LOGOUT";

// application template types
export const SAVE_APPLICATION_TEMPLATES = "SAVE_APPLICATION_TEMPLATES";
export const GET_APPLICATION_TEMPLATES = "GET_APPLICATION_TEMPLATES";
export const APPLICATION_TEMPLATES_ERROR = "APPLICATION_TEMPLATES_ERROR";
