export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_FAILED_LOGIN = "SET_FAILED_LOGIN";
export const SET_LOGOUT = "SET_LOGOUT";

// application template types
export const SAVE_APPLICATION_TEMPLATES = "SAVE_APPLICATION_TEMPLATES";
export const GET_APPLICATION_TEMPLATES = "GET_APPLICATION_TEMPLATES";
export const APPLICATION_TEMPLATES_ERROR = "APPLICATION_TEMPLATES_ERROR";

// application types
export const SAVE_APPLICATION = "SAVE_APPLICATION";
export const GET_APPLICATIONS = "GET_APPLICATIONS";
export const UPDATE_APPLICATION = "UPDATE_APPLICATION";
export const APPLICATION_ERROR = "APPLICATION_ERROR";

// course types
export const GET_COURSES = "GET_COURSES";
export const COURSES_ERROR = "COURSES_ERROR";
