version: '3'
services:

  db:
    image: postgres
    environment:
      POSTGRES_USER: canvas
      POSTGRES_PASSWORD: password
      POSTGRES_DB: canvas_development
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis

  canvas:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.stretch
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgresql://canvas:password@db/canvas_development
      - REDIS_URL=redis://redis
      - S3_BUCKET=name-of-your-bucket
      - S3_ACCESS_KEY_ID=minio
      - S3_SECRET_ACCESS_KEY=minio123
      - S3_HOST=s3:9000
      - S3_ENDPOINT=http://s3:9000
      - S3_PROTOCOL=http

  s3:
    image: minio/minio
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
    command: server /data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123

volumes:
  postgres-data:
  minio-data:
