version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - './frontend:/usr/src/app'
      - '/usr/src/app/node_modules'
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '5001:5001'
    volumes:
      - './backend:/usr/src/app'
      - '/usr/src/app/node_modules'
    environment:
      - NODE_ENV=development
      - DB_USERNAME=test
      - DB_PASSWORD=password
      - DB_HOST=mongodb
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - 'mongodb_data_container:/data/db'

volumes:
  mongodb_data_container:
