version: '3'
services:
  s3:
    image: minio/minio
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
      #expose
    command: server /data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123

volumes:
  minio-data:
